insert into nomebanco values ('1','BB','Banco do Brasil S. A.');
insert into nomebanco values ('2','BANCENTRAL','Banco Central do Brasil');
insert into nomebanco values ('3','BANCREVEA','Banco da Amazonia S.A.');
insert into nomebanco values ('4','POLIGONO','Banco do Nordeste do Brasil S.A.');
insert into nomebanco values ('7','BADEC','Banco Nacional do Desenvolvimento Economico e Social');
insert into nomebanco values ('8','MERIDIONAL','Banco Meridional do Brasil S.A.');
insert into nomebanco values ('21','BANESTES','Banco do Estado do Espirito Santo S.A.');
insert into nomebanco values ('22','CREDIREAL','Banco de Credito Real de Minas Gerais S.A.');
insert into nomebanco values ('24','BANDEPE','Banco do Estado de Pernanbuco S. A.');
insert into nomebanco values ('25','ALFA','Banco Alfa S. A.');
insert into nomebanco values ('27','BESCBANCO','Banco do Estado de Santa Catarina S. A.');
insert into nomebanco values ('28','BANEB','Banco do Estado da Bahia S. A.');
insert into nomebanco values ('29','BANERJ','Banco Banerj S. A.');
insert into nomebanco values ('30','PARAIBAN','Banco do Estado da Paraiba S. A. ');
insert into nomebanco values ('31','BEG','Banco do Estado de Goias S. A.');
insert into nomebanco values ('33','BANESPA','Banco do Estado de Sao Paulo S. A.');
insert into nomebanco values ('34','BEA','Banco do Estado do Amazonas S. A. ');
insert into nomebanco values ('35','SEDEBEC','Banco do Estado do Ceara S. A.');
insert into nomebanco values ('36','BANCOBEM','Banco do Estado do Maranhao S. A.');
insert into nomebanco values ('37','BANPARA','Banco do Estado do Para S. A. ');
insert into nomebanco values ('38','BANESTADO','Bando do Estado do Parana S. A.');
insert into nomebanco values ('39','BEPI','Banco do Estado do Piaui S. A. ');
insert into nomebanco values ('40','CARGILL','Banco Cargill S. A. ');
insert into nomebanco values ('41','BANRISUL','Banco do Estado do Rio Grande do Sul S. A.');
insert into nomebanco values ('42','JSAFRABANK','Banco J. Safra S. A.');
insert into nomebanco values ('44','BVA','Banco BVA S. A.');
insert into nomebanco values ('47','BANESE','Banco do Estado de Sergipe S. A.');
insert into nomebanco values ('48','BEMGE','Banco Bemge S. A.');
insert into nomebanco values ('70','REGIOBANK','Banco de Brasilia S. A. ');
insert into nomebanco values ('104','ECONOMICA','Caixa Economica Federal');
insert into nomebanco values ('106','ITABANCO','Banco Itabanco S. A. ');
insert into nomebanco values ('107','BBM','Banco BBM S. A.');
insert into nomebanco values ('109','CREDIBANCO','Credibanco S. A.');
insert into nomebanco values ('116','BNL','Banco BNL do Brasil S. A.');
insert into nomebanco values ('148','MULTI','Multi Banco S. A.');
insert into nomebanco values ('151','NOSSACAIXA','Caixa Economica do Estado de Sao Paulo S. A.');
insert into nomebanco values ('168','CCFBRASIL','Banco CCF Brasil S. A.');
insert into nomebanco values ('175','CONTINENTAL','Continental Banco S. A.');
insert into nomebanco values ('184','BANCO BBA','Banco BBA Creditanstalt S. A.');
insert into nomebanco values ('199','FINANCIAL','Banco Financial Portugues S. A. ');
insert into nomebanco values ('200','FICRISA','Banco Ficrisa Axelrud S. A. ');
insert into nomebanco values ('201','AXIAL','Banco Axial S. A.');
insert into nomebanco values ('204','INTERAMEX','Banco Inter American Express S. A. ');
insert into nomebanco values ('205','SULAMERICA','Banco Sul America Scandinavian S. A. ');
insert into nomebanco values ('208','PACTUAL','Banco Pactual S. A.');
insert into nomebanco values ('210','DRESDNER','Dresdner Bank Lateinamerika AG');
insert into nomebanco values ('211','SISTEMA','Banco Sistema S. A. ');
insert into nomebanco values ('212','MATONE','Banco Matone S. A.');
insert into nomebanco values ('213','ARBI','Banco Arbi S. A. ');
insert into nomebanco values ('214','DIBENS','Banco Dibens S. A.');
insert into nomebanco values ('215','GINKO','Banco America do Sul S. A.');
insert into nomebanco values ('216','MALCON','Banco Malcon S. A.');
insert into nomebanco values ('217','BCO JOHN DEERE','Banco Jonh Deere S. A. ');
insert into nomebanco values ('218','BBS','Banco Bonsucesso S. A.');
insert into nomebanco values ('219','ZOGBI','Banco Zobgi S. A.');
insert into nomebanco values ('221','FLEMING GRAPHUS','Banco Fleming Graphus S. A. ');
insert into nomebanco values ('222','AGF','Banco AGF Brasil S. A.');
insert into nomebanco values ('224','FIBRA','Banco Fibra S. A. ');
insert into nomebanco values ('225','BRASCAN','Banco Brascan S. A.');
insert into nomebanco values ('228','ICATU','Banco Icatu S. A.');
insert into nomebanco values ('229','CRUZEIRO','Banco Cruzeiro do Sul S. A. ');
insert into nomebanco values ('230','BEBECE','Banco Bandeirantes S. A.');
insert into nomebanco values ('231','VISTABANCO','Banco Boavista Intetlantico S. A.');
insert into nomebanco values ('232','INTERPART','Banco Interpart S. A.');
insert into nomebanco values ('233','GE CAPITAL','Banco GE Capital S. A. ');
insert into nomebanco values ('235','LIBERAL','Banco Liberal S. A. ');
insert into nomebanco values ('237','BRADESCO','Banco Bradesco S. A.');
insert into nomebanco values ('241','CLASSICO','Banco Classico S. A. ');
insert into nomebanco values ('242','EUROINVEST','Banco Euroinvest S. A. ');
insert into nomebanco values ('243','STOCK','Banco Stock Maxima S. A. ');
insert into nomebanco values ('244','BANCOCIDADE','Banco Cidade S. A.');
insert into nomebanco values ('246','ABC BRASIL','Banco ABC-Brasil S. A.');
insert into nomebanco values ('247','WDR','Banco Warburg Dillon Read S. A.');
insert into nomebanco values ('249','INVESTCRED','Banco Investcred S. A. ');
insert into nomebanco values ('250','SCHAHIN','Banco Schahin S. A.');
insert into nomebanco values ('252','FININVEST','Banco Fininvest S. A. ');
insert into nomebanco values ('254','PARANABANCO','Parana Banco S. A.');
insert into nomebanco values ('258','BANKERMES','Banco Induscred S. A. ');
insert into nomebanco values ('262','BOREAL','Banco Boreal S. A.');
insert into nomebanco values ('263','CACIQUE','Banco Cacique S. A. ');
insert into nomebanco values ('265','FATOR','Banco Fator S. A.');
insert into nomebanco values ('266','CEDULA','Banco Cedula S. A.');
insert into nomebanco values ('275','REALSA','Banco Real S. A.');
insert into nomebanco values ('291','BECEENE','Banco de Credito Nacional S. A.');
insert into nomebanco values ('294','GARANTIA','Banco de Credito Real do Rio Grande do Sul S. A. ');
insert into nomebanco values ('300','BANCNACION','Banco de la Nacion Argentina');
insert into nomebanco values ('318','BMG','Banco BMG S. A. ');
insert into nomebanco values ('320','BICBANCO','Banco Industrial e Comercial S. A.  ');
insert into nomebanco values ('341','ITAUBANCO','Banco Itau S. A.');
insert into nomebanco values ('346','CREDIONAIS','Banco Frances e Brasileiro');
insert into nomebanco values ('347','SUDAMERIS','Banco Sudameris Brasil S. A.');
insert into nomebanco values ('351','BOZNES','Banco Bozano Simonsen S. A.');
insert into nomebanco values ('353','SANTANDERBRASIL','Banco Santander Brasil S. A.');
insert into nomebanco values ('356','BANCOLANDA','Banco ABN Amro Real S. A.');
insert into nomebanco values ('366','SOGERAL','Banco Sogeral S. A.');
insert into nomebanco values ('370','BEALBANK','Banco Europeu para a America Latina S. A. ');
insert into nomebanco values ('376','CHASE','Banco Chase Manhattan S. A.');
insert into nomebanco values ('389','BANCANTIL','Banco Mercantil do Brasil S. A.');
insert into nomebanco values ('392','FINANSA','Banco Mercantil de Sao Paulo S. A.');
insert into nomebanco values ('394','BMC','Banco BMC S. A. ');
insert into nomebanco values ('399','HSBC BANK','HSBC Bank Brasil S. A. - Banco Multiplo');
insert into nomebanco values ('409','UNIBANCO','UNIBANCO - Uniao de Bancos Brasileiros S. A.');
insert into nomebanco values ('412','BANCAP','Banco Capital S. A.');
insert into nomebanco values ('422','SAFRABANK','Banco Safra S. A.');
insert into nomebanco values ('424','NOROESTE','Banco Santander Noroeste S. A. ');
insert into nomebanco values ('453','RURALMINAS','Banco Rural S. A.');
insert into nomebanco values ('456','TOHBANK','Banco de Tokio - Mitsubishi Brasil S. A. ');
insert into nomebanco values ('464','SUMITBANK','Banco Sumitomo Brasileiro S. A. ');
insert into nomebanco values ('472','INTERLOYD','Lloyds Bank PLC');
insert into nomebanco values ('477','CITIBANK','Citibank N. A.');
insert into nomebanco values ('479','BANKBOSTON','BankBoston Banco Multiplo S. A.');
insert into nomebanco values ('480','WACHOVIA','Banco Wachovia S. A. ');
insert into nomebanco values ('487','DEUTSCHE','Deutsche Bank S. A. - Banco Alemao');
insert into nomebanco values ('488','MORGANBANK','Morgan Guaranty Trust Company of New York');
insert into nomebanco values ('489','BFI','Banco Frances Internacional Brasil S. A. ');
insert into nomebanco values ('492','NEDERLANDEN','Banco Internacionale Nederlanden BAM');
insert into nomebanco values ('493','UNIONCA','Banco Union S. A. ');
insert into nomebanco values ('494','URUGUAYBANK','Banco de la Republica Oriental del Uruguay');
insert into nomebanco values ('495','BAPROSAO','Banco de la Provincia de Buenos Aires');
insert into nomebanco values ('496','EXTERIBANK','Banco Exterior de Espana S. A. ');
insert into nomebanco values ('498','CENTROBANCO','Centro Hispano Banco');
insert into nomebanco values ('502','BANSANDER','Banco Santander de Negocios S. A. ');
insert into nomebanco values ('505','CREDIT SUISSE','Banco Credit Suisse First Boston Garantia S. A. ');
insert into nomebanco values ('600','LUSO','Banco Luso Brasileiro S. A.');
insert into nomebanco values ('604','INDUSTRIAL','Banco Industrial do Brasil S. A. ');
insert into nomebanco values ('607','SANTOSNEVES','Banco Santos Neves S. A.');
insert into nomebanco values ('610','VR','Banco VR S. A.');
insert into nomebanco values ('611','PAULISTA','Banco Paulista S. A.');
insert into nomebanco values ('612','GUANABARA','Banco Guanabara S. A. ');
insert into nomebanco values ('613','PECUNIA','Banco Pecunia S. A. ');
insert into nomebanco values ('618','TENDENCIA','Banco Tendencia S. A.');
insert into nomebanco values ('623','PANAMERICANO','Banco Panamericano S. A.');
insert into nomebanco values ('625','ARAUCARIA','Banco Araucaria S. A.');
insert into nomebanco values ('626','FICSA','Banco Ficsa S. A.');
insert into nomebanco values ('630','INTERCAP','Banco Intercap S. A.');
insert into nomebanco values ('633','RENDIMENTO','Banco Rendimento S. A.');
insert into nomebanco values ('634','TRIANGULO','Banco Triangulo S. A. ');
insert into nomebanco values ('637','SOFISA','Banco Sofisa S. A.');
insert into nomebanco values ('638','PROSPER','Banco Prosper S. A.');
insert into nomebanco values ('641','BILBAO VIZCAYA','Banco Bilbao Vizcaya Argentaria Brasil S. A. ');
insert into nomebanco values ('643','PINE','Banco Pine S. A.');
insert into nomebanco values ('650','PEBB','Banco Pebb S. A.');
insert into nomebanco values ('653','INDUSVAL','Banco Indusval S. A.');
insert into nomebanco values ('654','RENNER','Banco A. J. Renner S. A. ');
insert into nomebanco values ('655','VOTORANTIM','Banco Votorantim S. A.');
insert into nomebanco values ('656','MATRIX','Banco Matrix S. A.');
insert into nomebanco values ('658','PORTOREAL','Banco Porto Real S. A. ');
insert into nomebanco values ('702','SANTOS','Banco Santos S. A.');
insert into nomebanco values ('707','DAYCOVAL','Banco Daycoval S. A.');
insert into nomebanco values ('719','BANIF PRIMUS','Banco Banif Primus S. A.');
insert into nomebanco values ('720','MAXINVEST','Banco Maxinvest S. A. ');
insert into nomebanco values ('721','CREDIBEL','Banco Credibel S. A.');
insert into nomebanco values ('722','BANINTER','Banco Interior Sao Paulo S. A.');
insert into nomebanco values ('725','FINANBANCO','Banco Finansinos S. A. ');
insert into nomebanco values ('729','FONTE CINDAM','Banco Fonte-Cindam S. A. ');
insert into nomebanco values ('732','MINAS','Banco Minas S. A. ');
insert into nomebanco values ('733','NACOESBANK','Banco das Nacoes S. A.');
insert into nomebanco values ('734','GERDAU','Banco Gerdau S. A.');
insert into nomebanco values ('735','POTTENCIAL ','Banco Pottencial S. A.');
insert into nomebanco values ('738','MORADA','Banco Morada S. A.');
insert into nomebanco values ('739','BGN','Banco BGN S. A.');
insert into nomebanco values ('740','BARCLAYS GALI','Banco Barclays e Galicia S. A. ');
insert into nomebanco values ('741','BRP','Banco Ribeirao Preto S. A. ');
insert into nomebanco values ('742','EQUATORIAL','Banco Equatorial S. A.');
insert into nomebanco values ('743','EMBLEMA','Banco Emblema S. A.');
insert into nomebanco values ('744','BOSTON N. A.','BankBoston N. A. ');
insert into nomebanco values ('745','CITIBANK','Banco Citibank S. A.');
insert into nomebanco values ('746','MODAL','Banco Modal S. A.');
insert into nomebanco values ('747','RAIOBANK','Banco RaboBank Internacional Brasil S. A. ');
insert into nomebanco values ('748','BANSICREDI','Banco Cooperativo Sicredi S. A. - Bansicredi');
insert into nomebanco values ('749','BRMSA BR','Banco Mercantil S. A. ');
insert into nomebanco values ('750','REPUBLIC NATION','Banco Republic National of New York (Brasil) . ');
insert into nomebanco values ('751','DBBBM','Dresdner Bank Brasil S. A. ');
insert into nomebanco values ('752','BNP','Banque Nationale de Paris Brasil S. A.');
insert into nomebanco values ('753','URBANK','Banco Comercial Uruguai S. A.');
insert into nomebanco values ('755','MERRYL LYNCH','Banco Merryl Lynch S. A. ');
insert into nomebanco values ('756','BANCOB','Banco Cooperativo do Brasil S. A. ');
insert into nomebanco values ('757','KEB','Banco KEB do Brasil S. A');