insert into estados (str_estado, str_uf) values ('Amazonas', 'AM');
insert into estados (str_estado, str_uf) values ('Amapa', 'AP');
insert into estados (str_estado, str_uf) values ('Acre', 'AC');
insert into estados (str_estado, str_uf) values ('Mato Grosso', 'MT');
insert into estados (str_estado, str_uf) values ('Mato Grosso do Sul', 'MS');
insert into estados (str_estado, str_uf) values ('Goias', 'GO');
insert into estados (str_estado, str_uf) values ('Para', 'PA');
insert into estados (str_estado, str_uf) values ('Paraiba', 'PB');
insert into estados (str_estado, str_uf) values ('Pernambuco', 'PE');
insert into estados (str_estado, str_uf) values ('Sergipe', 'SE');
insert into estados (str_estado, str_uf) values ('Ceara', 'CE');
insert into estados (str_estado, str_uf) values ('Sao Paulo', 'SP');
insert into estados (str_estado, str_uf) values ('Parana', 'PR');
insert into estados (str_estado, str_uf) values ('Rio Grando do Sul', 'RS');
insert into estados (str_estado, str_uf) values ('Rio Grande do Norte', 'RN');
insert into estados (str_estado, str_uf) values ('Rondonia', 'RO');
insert into estados (str_estado, str_uf) values ('Minas Gerais', 'MG');
insert into estados (str_estado, str_uf) values ('Bahia', 'BA');
insert into estados (str_estado, str_uf) values ('Tocantins', 'TO');
insert into estados (str_estado, str_uf) values ('Distrito Federal', 'DF');
insert into estados (str_estado, str_uf) values ('Rio de Janeiro', 'RJ');
insert into estados (str_estado, str_uf) values ('Espirito Santo', 'ES');
insert into estados (str_estado, str_uf) values ('Santa Catarina', 'SC');
insert into estados (str_estado, str_uf) values ('Alagoas', 'AL');
insert into estados (str_estado, str_uf) values ('Maranhao', 'MA');
insert into estados (str_estado, str_uf) values ('Piaui', 'PI');
insert into estados (str_estado, str_uf) values ('Roraima', 'RR');
