INSERT INTO placon (codigo,descricao) VALUES ('1','ATIVO CIRCULANTE');
INSERT INTO placon (codigo,descricao) VALUES ('1.1','DISPONIBILIDADES');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.1','Caixa');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.1.1','Dinheiro em Especie no Caixa');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.1.2','Cheques no Caixa');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.1.3','Boletos no Caixa');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.1.4','Promissorias no Caixa');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.2','Recursos de Caixa Pequena');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.3','Bancos Contas Movimento no Pais');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.4','Bancos Contas Movimento no Exterior');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.5','Bancos Contas Vinculadas');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.6','Depositos em Garantia e Caucoes em Dinheiro');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.7','Disponibilidades em Moedas Estrangeiras');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.8','Aplicacoes em Ouro');
INSERT INTO placon (codigo,descricao) VALUES ('1.1.9','Outras Disponibilidades');
INSERT INTO placon (codigo,descricao) VALUES ('1.2','TITULOS E VALORES MOBILIARIOS');
INSERT INTO placon (codigo,descricao) VALUES ('1.2.1','Clientes a Contas a Receber');
INSERT INTO placon (codigo,descricao) VALUES ('1.2.2','Aplicacoes de Renda Fixa');
INSERT INTO placon (codigo,descricao) VALUES ('1.2.3','Aplicacoes de Renda Variavel');
INSERT INTO placon (codigo,descricao) VALUES ('1.2.4','Titulos e Aplicacoes Vinculados');
INSERT INTO placon (codigo,descricao) VALUES ('1.2.9','Outros Titulos e Valores Mobiliarios a Receber');
INSERT INTO placon (codigo,descricao) VALUES ('1.3','ESTOQUES');
INSERT INTO placon (codigo,descricao) VALUES ('1.3.1','Estoque de Materias Primas');
INSERT INTO placon (codigo,descricao) VALUES ('1.3.2','Estoque de Producao em Elaboracao');
INSERT INTO placon (codigo,descricao) VALUES ('1.3.3','Estoque de Produtos Acabados');
INSERT INTO placon (codigo,descricao) VALUES ('1.3.4','Estoque de Mercadorias para Revenda');
INSERT INTO placon (codigo,descricao) VALUES ('1.3.5','Material de Reposicao na Prestacao de Servicos');
INSERT INTO placon (codigo,descricao) VALUES ('1.3.6','Material de Expediente');
INSERT INTO placon (codigo,descricao) VALUES ('1.3.9','Estoques - Contas Retificadoras');
INSERT INTO placon (codigo,descricao) VALUES ('1.4','CREDITOS TRIBUTARIOS');
INSERT INTO placon (codigo,descricao) VALUES ('1.4.1','Imposto de Renda');
INSERT INTO placon (codigo,descricao) VALUES ('1.4.2','Contribuicao Social');
INSERT INTO placon (codigo,descricao) VALUES ('1.4.3','ICMS - Imposto sobre a Circulacao de Mercadorias e Servicos');
INSERT INTO placon (codigo,descricao) VALUES ('1.4.4','IPI - Imposto sobre Produtos Industrializados');
INSERT INTO placon (codigo,descricao) VALUES ('1.4.5','ISS - Imposto sobre Servicos');
INSERT INTO placon (codigo,descricao) VALUES ('1.4.6','Cofins');
INSERT INTO placon (codigo,descricao) VALUES ('1.4.9','Outros Impostos e Taxas');
INSERT INTO placon (codigo,descricao) VALUES ('1.7','OUTROS CREDITOS');
INSERT INTO placon (codigo,descricao) VALUES ('1.7.1','Comissoes e Corretagens a Receber');
INSERT INTO placon (codigo,descricao) VALUES ('1.7.2','Dividendos / Bonificacoes em Dinheiro a Receber');
INSERT INTO placon (codigo,descricao) VALUES ('1.7.3','Outras Rendas a Receber');
INSERT INTO placon (codigo,descricao) VALUES ('1.7.5','Valores a Receber pela Venda de Bens');
INSERT INTO placon (codigo,descricao) VALUES ('1.7.9','Outras Contas a Receber');
INSERT INTO placon (codigo,descricao) VALUES ('1.8','DIVERSOS ATIVOS CIRCULANTES');
INSERT INTO placon (codigo,descricao) VALUES ('1.8.1','Adiantamentos e Antecipacoes Salariais');
INSERT INTO placon (codigo,descricao) VALUES ('1.8.2','Adiantamentos a Fornecedores');
INSERT INTO placon (codigo,descricao) VALUES ('1.8.3','Adiantamentos para Pagamentos de Nossa Conta');
INSERT INTO placon (codigo,descricao) VALUES ('1.8.4','Emprestimo de Titulos e Valores Mobiliarios');
INSERT INTO placon (codigo,descricao) VALUES ('1.8.5','Importacoes em Andamento');
INSERT INTO placon (codigo,descricao) VALUES ('1.8.6','Devedores Diversos - Pais');
INSERT INTO placon (codigo,descricao) VALUES ('1.8.7','Devedores Diversos - Exterior');
INSERT INTO placon (codigo,descricao) VALUES ('1.8.8','Outras Contas do Ativo Circulante');
INSERT INTO placon (codigo,descricao) VALUES ('1.8.9','Diversos Ativos Circulantes - Contas Retificadoras');
INSERT INTO placon (codigo,descricao) VALUES ('1.9','DESPESAS ANTECIPADAS');
INSERT INTO placon (codigo,descricao) VALUES ('1.9.1','Estoques de Materiais de Escritorio');
INSERT INTO placon (codigo,descricao) VALUES ('1.9.2','Seguros a Apropriar');
INSERT INTO placon (codigo,descricao) VALUES ('1.9.3','Juros Pagos Antecipadamente');
INSERT INTO placon (codigo,descricao) VALUES ('1.9.4','Adiantamentos para Despesas');
INSERT INTO placon (codigo,descricao) VALUES ('1.9.5','Antecipacao do 13o. Salario');
INSERT INTO placon (codigo,descricao) VALUES ('1.9.6','Estoques de Sucata');
INSERT INTO placon (codigo,descricao) VALUES ('1.9.9','Outras Despesas Antecipadas');
INSERT INTO placon (codigo,descricao) VALUES ('2','REALIZAVEL A LONGO PRAZO');
INSERT INTO placon (codigo,descricao) VALUES ('2.1','VALORES E BENS');
INSERT INTO placon (codigo,descricao) VALUES ('2.1.1','Adiantamentos por Conta de Imobilizacoes');
INSERT INTO placon (codigo,descricao) VALUES ('2.1.2','Imoveis Destinados a Venda');
INSERT INTO placon (codigo,descricao) VALUES ('2.1.3','Imoveis em Construcao');
INSERT INTO placon (codigo,descricao) VALUES ('2.1.4','Estoque de Reposicao do Permanente');
INSERT INTO placon (codigo,descricao) VALUES ('2.1.5','Antecipacao de Valores Residuais de Arrendamento Mercantil');
INSERT INTO placon (codigo,descricao) VALUES ('2.1.9','Outros Valores e Bens a Longo Prazo');
INSERT INTO placon (codigo,descricao) VALUES ('2.2','GARANTIAS E CAUCOES');
INSERT INTO placon (codigo,descricao) VALUES ('2.2.1','Garantias e Caucoes - Em Titulos');
INSERT INTO placon (codigo,descricao) VALUES ('2.2.2','Garantias e Caucoes - Em Bens Moveis');
INSERT INTO placon (codigo,descricao) VALUES ('2.2.3','Garantias e Caucoes - Em Imoveis');
INSERT INTO placon (codigo,descricao) VALUES ('2.2.9','Outras Garantias e Caucoes');
INSERT INTO placon (codigo,descricao) VALUES ('2.3','TITULOS E VALORES MOBILIARIOS');
INSERT INTO placon (codigo,descricao) VALUES ('2.3.1','TVM de Sociedades em Regime Especial');
INSERT INTO placon (codigo,descricao) VALUES ('2.3.2','Participacoes em Sociedades em Regime Especial');
INSERT INTO placon (codigo,descricao) VALUES ('2.3.3','Opcoes por Incentivos Fiscais');
INSERT INTO placon (codigo,descricao) VALUES ('2.3.8','Outros Titulos e Valores Mobiliarios de Longo Prazo');
INSERT INTO placon (codigo,descricao) VALUES ('2.3.9','TVM de Longo Prazo - Contas Retificadoras');
INSERT INTO placon (codigo,descricao) VALUES ('2.4','DEPOSITOS JUDICIAIS');
INSERT INTO placon (codigo,descricao) VALUES ('2.4.1','Depositos Judiciais - Trabalhistas');
INSERT INTO placon (codigo,descricao) VALUES ('2.4.2','Depositos Judiciais - Fiscais e Tributarios');
INSERT INTO placon (codigo,descricao) VALUES ('2.4.9','Outros Depositos Judiciais');
INSERT INTO placon (codigo,descricao) VALUES ('2.5','IMOVEIS PARA LOCACAO OU VENDA');
INSERT INTO placon (codigo,descricao) VALUES ('2.5.1','Imoveis para Locacao ou Venda - Terrenos');
INSERT INTO placon (codigo,descricao) VALUES ('2.5.2','Imoveis para Locacao ou Venda - Escritorios');
INSERT INTO placon (codigo,descricao) VALUES ('2.5.3','Imoveis para Locacao ou Venda - Galpoes');
INSERT INTO placon (codigo,descricao) VALUES ('2.5.4','Imoveis para Locacao ou Venda - Salas');
INSERT INTO placon (codigo,descricao) VALUES ('2.5.5','Imoveis para Locacao ou Venda - Lojas');
INSERT INTO placon (codigo,descricao) VALUES ('2.5.9','Outros Imoveis para Locacao e Venda');
INSERT INTO placon (codigo,descricao) VALUES ('2.9','OUTRAS CONTAS DO REALIZAVEL');
INSERT INTO placon (codigo,descricao) VALUES ('2.9.1','Creditos com Pessoas Ligadas');
INSERT INTO placon (codigo,descricao) VALUES ('2.9.2','Creditos com Empresas Ligadas');
INSERT INTO placon (codigo,descricao) VALUES ('2.9.3','Adiantamentos por Conta de Imobilizacoes');
INSERT INTO placon (codigo,descricao) VALUES ('2.9.4','Creditos em Sociedades em Regime Especial');
INSERT INTO placon (codigo,descricao) VALUES ('2.9.5','Emprestimos e Depositos Compulsorios');
INSERT INTO placon (codigo,descricao) VALUES ('2.9.9','Diversas Outras Contas do Realizavel');
INSERT INTO placon (codigo,descricao) VALUES ('3','ATIVO PERMANENTE');
INSERT INTO placon (codigo,descricao) VALUES ('3.1','INVESTIMENTOS');
INSERT INTO placon (codigo,descricao) VALUES ('3.1.1','Investimentos em Controladas');
INSERT INTO placon (codigo,descricao) VALUES ('3.1.2','Investimentos em Coligadas');
INSERT INTO placon (codigo,descricao) VALUES ('3.1.3','Investimentos por Incentivos Fiscais');
INSERT INTO placon (codigo,descricao) VALUES ('3.1.4','Titulos Patrimoniais');
INSERT INTO placon (codigo,descricao) VALUES ('3.1.5','Investimentos em Empresas Privatizadas');
INSERT INTO placon (codigo,descricao) VALUES ('3.1.7','Participacoes em Outras Empresas');
INSERT INTO placon (codigo,descricao) VALUES ('3.1.8','Obras de Arte e Antiguidades');
INSERT INTO placon (codigo,descricao) VALUES ('3.1.9','Outros Investimentos');
INSERT INTO placon (codigo,descricao) VALUES ('3.2','IMOBILIZADO DE USO');
INSERT INTO placon (codigo,descricao) VALUES ('3.2.1','Terrenos');
INSERT INTO placon (codigo,descricao) VALUES ('3.2.2','Edificios e Construcoes');
INSERT INTO placon (codigo,descricao) VALUES ('3.2.3','Equipamentos, Maquinas e Instalacoes Industriais');
INSERT INTO placon (codigo,descricao) VALUES ('3.2.4','Moveis, Utensilios e Instalacoes Nao Industriais');
INSERT INTO placon (codigo,descricao) VALUES ('3.2.5','Bens Oriundos de Arrendamento Mercantil');
INSERT INTO placon (codigo,descricao) VALUES ('3.2.6','Recursos Minerais, Recursos Florestais e Direitos de Exploracao');
INSERT INTO placon (codigo,descricao) VALUES ('3.2.7','Veiculos');
INSERT INTO placon (codigo,descricao) VALUES ('3.2.8','Sistemas de Comunicacao e de Processamento de Dados');
INSERT INTO placon (codigo,descricao) VALUES ('3.2.9','Aplicacoes em Bens Intangiveis');
INSERT INTO placon (codigo,descricao) VALUES ('3.3','DIFERIDO');
INSERT INTO placon (codigo,descricao) VALUES ('3.3.1','Despesas Pre-Operacionais');
INSERT INTO placon (codigo,descricao) VALUES ('3.3.2','Despesas com Producoes Cientificas e Tecnologicas');
INSERT INTO placon (codigo,descricao) VALUES ('3.3.3','Demais Aplicacoes em Despesas Amortizaveis');
INSERT INTO placon (codigo,descricao) VALUES ('3.3.4','Benfeitorias em Imoveis de Terceiros');
INSERT INTO placon (codigo,descricao) VALUES ('3.3.5','Agios na Incorporacao, Fusao ou Cisao');
INSERT INTO placon (codigo,descricao) VALUES ('3.3.6','Exploracao de Recursos Florestais');
INSERT INTO placon (codigo,descricao) VALUES ('3.3.7','Prospeccao e Lavra de Recursos Minerais');
INSERT INTO placon (codigo,descricao) VALUES ('3.3.9','Outras Contas do Diferido');
INSERT INTO placon (codigo,descricao) VALUES ('4','PASSIVO CIRCULANTE');
INSERT INTO placon (codigo,descricao) VALUES ('4.1','Fornecedores');
INSERT INTO placon (codigo,descricao) VALUES ('4.1.1','Fornecedores no Pais');
INSERT INTO placon (codigo,descricao) VALUES ('4.1.2','Fornecedores no Exterior');
INSERT INTO placon (codigo,descricao) VALUES ('4.1.9','Outros Fornecedores');
INSERT INTO placon (codigo,descricao) VALUES ('4.2','Financiamentos de Curto Prazo');
INSERT INTO placon (codigo,descricao) VALUES ('4.2.1','Bancos Oficiais Federais');
INSERT INTO placon (codigo,descricao) VALUES ('4.2.2','Bancos Oficiais Estaduais');
INSERT INTO placon (codigo,descricao) VALUES ('4.2.3','Bancos Privados no Brasil');
INSERT INTO placon (codigo,descricao) VALUES ('4.2.4','Bancos Oficiais no Exterior');
INSERT INTO placon (codigo,descricao) VALUES ('4.2.5','Outros Bancos no Exterior');
INSERT INTO placon (codigo,descricao) VALUES ('4.2.6','Empresas de Factoring / Forfaiting');
INSERT INTO placon (codigo,descricao) VALUES ('4.2.9','Outros Financiamentos de Curto Prazo');
INSERT INTO placon (codigo,descricao) VALUES ('4.3','Obrigacoes Fiscais e Tributarias');
INSERT INTO placon (codigo,descricao) VALUES ('4.3.1','Imposto de Renda Retido na Fonte');
INSERT INTO placon (codigo,descricao) VALUES ('4.3.2','Imposto de Renda e Contribuicao Social a Pagar');
INSERT INTO placon (codigo,descricao) VALUES ('4.3.3','Outros - Impostos Federais');
INSERT INTO placon (codigo,descricao) VALUES ('4.3.4','Impostos Estaduais');
INSERT INTO placon (codigo,descricao) VALUES ('4.3.5','Impostos Municipais');
INSERT INTO placon (codigo,descricao) VALUES ('4.3.9','Outros Obrigacoes Fiscais e Tributarias');
INSERT INTO placon (codigo,descricao) VALUES ('4.4','Obrigacoes Trabalhistas e Previdenciarias');
INSERT INTO placon (codigo,descricao) VALUES ('4.4.1','Ordenados e Salarios a Pagar');
INSERT INTO placon (codigo,descricao) VALUES ('4.4.2','Autonomos a Pessoas Fisicas');
INSERT INTO placon (codigo,descricao) VALUES ('4.4.3','Terceirizados a Pessoas Juridicas');
INSERT INTO placon (codigo,descricao) VALUES ('4.4.4','Contribuicao ao INSS');
INSERT INTO placon (codigo,descricao) VALUES ('4.4.5','FGTS');
INSERT INTO placon (codigo,descricao) VALUES ('4.4.6','Contribuicao Sindical');
INSERT INTO placon (codigo,descricao) VALUES ('4.4.7','Indenizacoes Trabalhistas a Pagar');
INSERT INTO placon (codigo,descricao) VALUES ('4.4.8','Debitos Previdenciarios a Pagar');
INSERT INTO placon (codigo,descricao) VALUES ('4.4.9','Outros Obrigacoes Trabalhistas e Previdenciarias');
INSERT INTO placon (codigo,descricao) VALUES ('4.5','Obrigacoes Sociais e Estatutarias');
INSERT INTO placon (codigo,descricao) VALUES ('4.5.1','Antecipacao de Dividendos a Pagar');
INSERT INTO placon (codigo,descricao) VALUES ('4.5.2','Dividendos a Distribuir');
INSERT INTO placon (codigo,descricao) VALUES ('4.5.3','Participacao nos Lucros a Pagar');
INSERT INTO placon (codigo,descricao) VALUES ('4.5.4','Juros sobre o Capital a Pagar');
INSERT INTO placon (codigo,descricao) VALUES ('4.5.9','Outros Dividendos e Lucros a Pagar');
INSERT INTO placon (codigo,descricao) VALUES ('4.9','Outras Obrigacoes');
INSERT INTO placon (codigo,descricao) VALUES ('4.9.9','Diversas Outras Obrigacoes');
INSERT INTO placon (codigo,descricao) VALUES ('5','EXIGIVEL A LONGO PRAZO');
INSERT INTO placon (codigo,descricao) VALUES ('5.1','Fornecedores');
INSERT INTO placon (codigo,descricao) VALUES ('5.1.1','Fornecedores de Bens do Ativo Permanente');
INSERT INTO placon (codigo,descricao) VALUES ('5.1.9','Outros Fornecedores de Longo Prazo');
INSERT INTO placon (codigo,descricao) VALUES ('5.2','Financiamentos de Longo Prazo');
INSERT INTO placon (codigo,descricao) VALUES ('5.2.1','Bancos Oficiais Federais');
INSERT INTO placon (codigo,descricao) VALUES ('5.2.2','Bancos Oficiais Estaduais');
INSERT INTO placon (codigo,descricao) VALUES ('5.2.3','Bancos Privados no Brasil');
INSERT INTO placon (codigo,descricao) VALUES ('5.2.4','Bancos Oficiais no Exterior');
INSERT INTO placon (codigo,descricao) VALUES ('5.2.5.','Outros Bancos no Exterior');
INSERT INTO placon (codigo,descricao) VALUES ('5.2.6','Empresas de Factoring / Forfaiting');
INSERT INTO placon (codigo,descricao) VALUES ('5.2.9','Outros Financiamentos de Longo Prazo');
INSERT INTO placon (codigo,descricao) VALUES ('5.3','Obrigacoes Fiscais e Tributarias');
INSERT INTO placon (codigo,descricao) VALUES ('5.3.1','Imposto de Renda Diferido');
INSERT INTO placon (codigo,descricao) VALUES ('5.3.2','Parcelamento de Debitos Tributarios Federais');
INSERT INTO placon (codigo,descricao) VALUES ('5.3.3','Parcelamento de Debitos Tributarios Estaduais');
INSERT INTO placon (codigo,descricao) VALUES ('5.3.4','Parcelamento de Debitos Tributarios Municipais');
INSERT INTO placon (codigo,descricao) VALUES ('5.3.9','Outras Obrigacoes Fiscais e Tributarias');
INSERT INTO placon (codigo,descricao) VALUES ('5.4','Obrigacoes Trabalhistas e Previdenciarias');
INSERT INTO placon (codigo,descricao) VALUES ('5.4.1','Acoes Judiciais Trabalhistas');
INSERT INTO placon (codigo,descricao) VALUES ('5.4.2','Acoes Judiciais Previdenciarias');
INSERT INTO placon (codigo,descricao) VALUES ('5.4.3','Parcelamento de Debitos Trabalhistas');
INSERT INTO placon (codigo,descricao) VALUES ('5.4.4','Parcelamento de Debitos Previdenciarios');
INSERT INTO placon (codigo,descricao) VALUES ('5.4.9','Outras Obrigacoes Trabalhistas e Previdenciarias');
INSERT INTO placon (codigo,descricao) VALUES ('5.5','Obrigacoes Sociais e Estatutarias');
INSERT INTO placon (codigo,descricao) VALUES ('5.5.9','Outras Obrigacoes Sociais e Estatutarias');
INSERT INTO placon (codigo,descricao) VALUES ('5.6','Creditos de Ligadas');
INSERT INTO placon (codigo,descricao) VALUES ('5.6.1','Empresas Controladas');
INSERT INTO placon (codigo,descricao) VALUES ('5.6.2','Empresas Coligadas');
INSERT INTO placon (codigo,descricao) VALUES ('5.6.3','Administradores');
INSERT INTO placon (codigo,descricao) VALUES ('5.6.4','Controladores');
INSERT INTO placon (codigo,descricao) VALUES ('5.6.5','Acionistas Minoritarios');
INSERT INTO placon (codigo,descricao) VALUES ('5.6.9','Outros Creditos com Ligadas');
INSERT INTO placon (codigo,descricao) VALUES ('5.9','Outras Contas do Exigivel');
INSERT INTO placon (codigo,descricao) VALUES ('5.9.9','Diversas Outras Contas do Exigivel');
INSERT INTO placon (codigo,descricao) VALUES ('6','RESULTADO DE EXERCICIOS FUTUROS');
INSERT INTO placon (codigo,descricao) VALUES ('6.1','Receitas de Exercicios Futuros');
INSERT INTO placon (codigo,descricao) VALUES ('6.1.1','Receitas do Exercicio Seguinte');
INSERT INTO placon (codigo,descricao) VALUES ('6.1.2','Receitas do Demais Exercicios Futuros');
INSERT INTO placon (codigo,descricao) VALUES ('6.1.3','Desagios na Aquisicao de Participacoes Societarias');
INSERT INTO placon (codigo,descricao) VALUES ('6.1.4','Desagios na Incorporacao, Fusao e Cisao');
INSERT INTO placon (codigo,descricao) VALUES ('6.1.5','Desagios na Aquisicao de Empresas Privatizadas');
INSERT INTO placon (codigo,descricao) VALUES ('6.1.9','Outras Receitas de Exercicios Futuros');
INSERT INTO placon (codigo,descricao) VALUES ('6.2','Custos e Despesas de Exercicios Futuros');
INSERT INTO placon (codigo,descricao) VALUES ('6.2.1','Custos de Exercicios Futuros');
INSERT INTO placon (codigo,descricao) VALUES ('6.2.2','Despesas de Exercicios Futuros');
INSERT INTO placon (codigo,descricao) VALUES ('6.2.9','Outros Custos e Despesas de Exercicios Futuros');
INSERT INTO placon (codigo,descricao) VALUES ('6.3','Reservas de Reavaliacao de Ativos');
INSERT INTO placon (codigo,descricao) VALUES ('6.3.1','Reavaliacao de Realizaveis a Longo Prazo');
INSERT INTO placon (codigo,descricao) VALUES ('6.3.2','Reavaliacao de Bens do Permanente');
INSERT INTO placon (codigo,descricao) VALUES ('6.3.9','Outras Reservas de Reavaliacao de Ativos');
INSERT INTO placon (codigo,descricao) VALUES ('6.9','Provisao para Impostos sobre Lucros Diferidos');
INSERT INTO placon (codigo,descricao) VALUES ('6.9.1','Imposto de Renda Diferido');
INSERT INTO placon (codigo,descricao) VALUES ('6.9.2','Contribuicao Social Diferida');
INSERT INTO placon (codigo,descricao) VALUES ('6.9.9','Outras Provisoes para Impostos sobre Lucros Diferidos');
INSERT INTO placon (codigo,descricao) VALUES ('7','PATRIMONIO LIQUIDO');
INSERT INTO placon (codigo,descricao) VALUES ('7.1','CAPITAL SOCIAL');
INSERT INTO placon (codigo,descricao) VALUES ('7.1.1','Capital de Domiciliados no Pais a Pessoas Fisicas');
INSERT INTO placon (codigo,descricao) VALUES ('7.1.2','Capital de Domiciliados no Pais a Pessoas Juridicas');
INSERT INTO placon (codigo,descricao) VALUES ('7.1.3','Capital de Domiciliados no Exterior a Pessoas Fisicas');
INSERT INTO placon (codigo,descricao) VALUES ('7.1.4','Capital de Domiciliados no Exterior a Pessoas Juridicas');
INSERT INTO placon (codigo,descricao) VALUES ('7.1.8','Capital Subscrito a Integralizar');
INSERT INTO placon (codigo,descricao) VALUES ('7.1.9','Capital Nao Subscrito a Realizar');
INSERT INTO placon (codigo,descricao) VALUES ('7.2','RESERVAS');
INSERT INTO placon (codigo,descricao) VALUES ('7.2.1','Reservas Legais e Estatutarias');
INSERT INTO placon (codigo,descricao) VALUES ('7.2.2','Reservas de Capital');
INSERT INTO placon (codigo,descricao) VALUES ('7.2.3','Reservas de Lucros');
INSERT INTO placon (codigo,descricao) VALUES ('7.2.4','Reservas para Aumento de Capital');
INSERT INTO placon (codigo,descricao) VALUES ('7.2.5','Reservas de Contingencias');
INSERT INTO placon (codigo,descricao) VALUES ('7.2.7','Reservas de Reavaliacao');
INSERT INTO placon (codigo,descricao) VALUES ('7.2.9','Outras Reservas');
INSERT INTO placon (codigo,descricao) VALUES ('7.3','ACOES EM TESOURARIA');
INSERT INTO placon (codigo,descricao) VALUES ('7.3.1','Acoes Preferenciais');
INSERT INTO placon (codigo,descricao) VALUES ('7.3.2','Acoes Ordinarias');
INSERT INTO placon (codigo,descricao) VALUES ('7.3.3','Debentures Conversiveis');
INSERT INTO placon (codigo,descricao) VALUES ('7.3.4','Debentures Inconversiveis');
INSERT INTO placon (codigo,descricao) VALUES ('7.3.9','Outras Acoes em Tesouraria');
INSERT INTO placon (codigo,descricao) VALUES ('7.9','LUCROS/PREJUIZOS ACUMULADOS');
INSERT INTO placon (codigo,descricao) VALUES ('7.9.1','Lucros Acumulados de Exercicios Anteriores');
INSERT INTO placon (codigo,descricao) VALUES ('7.9.2','Lucro do Exercicio');
INSERT INTO placon (codigo,descricao) VALUES ('7.9.3','Prejuizos Fiscais de Exercicios Anteriores');
INSERT INTO placon (codigo,descricao) VALUES ('7.9.4','Prejuizo Fiscal do Exercicio');
INSERT INTO placon (codigo,descricao) VALUES ('7.9.5','Sobras Acumuladas de Exercicios Anteriores');
INSERT INTO placon (codigo,descricao) VALUES ('7.9.6','Sobras do Exercicio');
INSERT INTO placon (codigo,descricao) VALUES ('8','CONTAS DE RESULTADO CREDORAS - RECEITAS');
INSERT INTO placon (codigo,descricao) VALUES ('8.1','RECEITAS OPERACIONAIS');
INSERT INTO placon (codigo,descricao) VALUES ('8.1.1','Receita da Exportacao Incentivada');
INSERT INTO placon (codigo,descricao) VALUES ('8.1.2','Receita da Exportacao Nao Incentivada');
INSERT INTO placon (codigo,descricao) VALUES ('8.1.3','Receita da Venda no Mercado Interno de Produtos de Fabricacao Propria');
INSERT INTO placon (codigo,descricao) VALUES ('8.1.4','Receita da Revenda a Vista de Mercadorias no Varejo');
INSERT INTO placon (codigo,descricao) VALUES ('8.1.5','Receita da Revenda a Prazo de Mercadorias no Varejo');
INSERT INTO placon (codigo,descricao) VALUES ('8.1.6','Receita da Prestacao de Servicos');
INSERT INTO placon (codigo,descricao) VALUES ('8.1.7','Receita de Revenda de Mercadorias no Atacado');
INSERT INTO placon (codigo,descricao) VALUES ('8.2','Outras Receitas Operacionais');
INSERT INTO placon (codigo,descricao) VALUES ('8.2.1','Resultado Positivo de Participacoes Societarias');
INSERT INTO placon (codigo,descricao) VALUES ('8.2.2','Resultado Positivo em Sociedades em Conta de Participacao');
INSERT INTO placon (codigo,descricao) VALUES ('8.2.3','Receitas Financeiras');
INSERT INTO placon (codigo,descricao) VALUES ('8.2.4','Receitas de Aluguel');
INSERT INTO placon (codigo,descricao) VALUES ('8.2.5','Receitas de Amortizacao de Desagios');
INSERT INTO placon (codigo,descricao) VALUES ('8.2.6','Ganhos de Capital');
INSERT INTO placon (codigo,descricao) VALUES ('8.2.9','Diversas Receitas Operacionais');
INSERT INTO placon (codigo,descricao) VALUES ('8.3','Receitas Nao Operacionais');
INSERT INTO placon (codigo,descricao) VALUES ('8.3.1','Receitas da Alienacao de Bens do Ativo Permanente');
INSERT INTO placon (codigo,descricao) VALUES ('8.3.2','Receitas da Alienacao de Direitos do Ativo Permanente');
INSERT INTO placon (codigo,descricao) VALUES ('8.3.3','Receitas da Alienacao de Bens do Realizavel de Longo Prazo');
INSERT INTO placon (codigo,descricao) VALUES ('8.3.4','Receitas da Alienacao de Direitos do Realizavel de Longo Prazo');
INSERT INTO placon (codigo,descricao) VALUES ('8.3.5','Receita da Venda se Sucata');
INSERT INTO placon (codigo,descricao) VALUES ('8.3.6','Receita das Unidades Imobiliarias Vendidas');
INSERT INTO placon (codigo,descricao) VALUES ('8.3.9','Outras Receitas Nao Operacionais');
INSERT INTO placon (codigo,descricao) VALUES ('8.9','Outras Receitas');
INSERT INTO placon (codigo,descricao) VALUES ('8.9.1','Reversao do Saldo de Provisoes Operacionais');
INSERT INTO placon (codigo,descricao) VALUES ('8.9.2','Reversao do Saldo de Provisoes Nao Operacionais');
INSERT INTO placon (codigo,descricao) VALUES ('8.9.9','Diversas Receitas Eventuais');
INSERT INTO placon (codigo,descricao) VALUES ('9','CONTAS DE RESULTADO DEVEDORAS - CUSTOS E DESPESAS');
INSERT INTO placon (codigo,descricao) VALUES ('9.1','CUSTOS');
INSERT INTO placon (codigo,descricao) VALUES ('9.1.1','Custos dos Produtos de Fabricacao Propria');
INSERT INTO placon (codigo,descricao) VALUES ('9.1.2','Custo das Mercadorias Revendidas');
INSERT INTO placon (codigo,descricao) VALUES ('9.1.3','Custo do Servicos Prestados');
INSERT INTO placon (codigo,descricao) VALUES ('9.1.9','Outros Custos');
INSERT INTO placon (codigo,descricao) VALUES ('9.2','DESPESAS OPERACIONAIS');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.0','Remuneracoes e Encargos Sociais');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.1','Contribuicoes e Doacoes');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.2','Despesas Incentivadas e Demais Beneficios a Empregados');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.3','Impostos e Taxas');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.4','Arrendamentos Mercantis e Alugueis');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.5','Depreciacoes e Despesas de Conservacao dos Bens e das Instalacoes');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.6','Despesas com Royalties e Assistencia Tecnica e com Pesquisas Cientificas e Tecnologicas');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.7','Propaganda e Publicidade');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.8','Provisoes e Multas');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.9','Outras Despesas Operacionais');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.10','Compras a Vista de Mercadorias p/ Estoque');
INSERT INTO placon (codigo,descricao) VALUES ('9.2.11','Compras a Prazo de Mercadorias p/ Estoque');
INSERT INTO placon (codigo,descricao) VALUES ('9.3','DESPESAS NAO OPERACIONAIS');
INSERT INTO placon (codigo,descricao) VALUES ('9.3.1','Resultado Negativo de Participacoes Societarias');
INSERT INTO placon (codigo,descricao) VALUES ('9.3.2','Resultado Negativo em Sociedades em Conta de Participacao');
INSERT INTO placon (codigo,descricao) VALUES ('9.3.3','Despesas Financeiras');
INSERT INTO placon (codigo,descricao) VALUES ('9.3.5','Juros sobre o Capital');
INSERT INTO placon (codigo,descricao) VALUES ('9.3.7','Perdas de Capital');
INSERT INTO placon (codigo,descricao) VALUES ('9.3.9','Outras Despesas Nao Operacionais');
INSERT INTO placon (codigo,descricao) VALUES ('9.4','DESPESAS COM ATIVIDADES RURAIS');
INSERT INTO placon (codigo,descricao) VALUES ('9.4.1','Remuneracoes, Encargos Sociais e Provisoes Correlatas');
INSERT INTO placon (codigo,descricao) VALUES ('9.4.2','Contribuicoes e Doacoes');
INSERT INTO placon (codigo,descricao) VALUES ('9.4.3','Despesas Incentivadas e Demais Beneficios a Empregados');
INSERT INTO placon (codigo,descricao) VALUES ('9.4.4','Impostos e Taxas');
INSERT INTO placon (codigo,descricao) VALUES ('9.4.5','Arrendamentos e Alugueis');
INSERT INTO placon (codigo,descricao) VALUES ('9.4.6','Depreciacoes e Despesas de Conservacao dos Bens e das Instalacoes');
INSERT INTO placon (codigo,descricao) VALUES ('9.4.7','Provisoes e Multas');
INSERT INTO placon (codigo,descricao) VALUES ('9.4.8','Propaganda e Publicidade');
INSERT INTO placon (codigo,descricao) VALUES ('9.4.9','Outras Despesas Operacionais');
INSERT INTO placon (codigo,descricao) VALUES ('9.9','DISTRIBUICAO DE RESULTADOS');
INSERT INTO placon (codigo,descricao) VALUES ('9.9.1','Participacoes de Debentures');
INSERT INTO placon (codigo,descricao) VALUES ('9.9.2','Participacoes de Empregados');
INSERT INTO placon (codigo,descricao) VALUES ('9.9.3','Participacao dos Administradores e das Partes Beneficiarias');
INSERT INTO placon (codigo,descricao) VALUES ('9.9.4','Contribuicoes para Assistencia e Previdencia dos Empregados');
INSERT INTO placon (codigo,descricao) VALUES ('9.9.5','Contribuicao Social Sobre o Lucro Liquido');
INSERT INTO placon (codigo,descricao) VALUES ('9.9.6','Provisao Para Imposto de Renda');
INSERT INTO placon (codigo,descricao) VALUES ('9.9.9','Dividendos');
INSERT INTO placon (codigo,descricao) VALUES ('0','CONTAS DE COMPENSACAO');
INSERT INTO placon (codigo,descricao) VALUES ('0.1','CONTAS DE COMPENSACAO ATIVA');
INSERT INTO placon (codigo,descricao) VALUES ('0.1.1','Contratos');
INSERT INTO placon (codigo,descricao) VALUES ('0.1.2','Custodia');
INSERT INTO placon (codigo,descricao) VALUES ('0.1.3','Administracao de Bens');
INSERT INTO placon (codigo,descricao) VALUES ('0.1.4','Seguros');
INSERT INTO placon (codigo,descricao) VALUES ('0.1.9','Outras Contas de Compensacao');
INSERT INTO placon (codigo,descricao) VALUES ('0.2','CONTAS DE COMPENSACAO PASSIVA');
INSERT INTO placon (codigo,descricao) VALUES ('0.2.1','Contratos');
INSERT INTO placon (codigo,descricao) VALUES ('0.2.2','Custodia');
INSERT INTO placon (codigo,descricao) VALUES ('0.2.3','Administracao de Bens');
INSERT INTO placon (codigo,descricao) VALUES ('0.2.4','Seguros');
INSERT INTO placon (codigo,descricao) VALUES ('0.2.9','Outras Contas de Compensacao');
